# Generated by Django 5.1.4 on 2024-12-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key_skills', models.TextField()),
                ('salary', models.FloatField(blank=True, null=True)),
                ('area_name', models.CharField(max_length=255)),
                ('published_at', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Vacancy_From_HH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('skills', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'vacancy_from_hh',
            },
        ),
    ]
