# Generated by Django 5.1.4 on 2024-12-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key_skills', models.CharField(blank=True, max_length=1000, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('area_name', models.CharField(max_length=255)),
                ('published_at', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Job_Area_Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(blank=True, null=True)),
                ('area_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'area_count',
            },
        ),
        migrations.CreateModel(
            name='Job_Area_Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(blank=True, null=True)),
                ('area_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'area_salary',
            },
        ),
        migrations.CreateModel(
            name='Job_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('key_skill', models.CharField(max_length=100)),
                ('published_at', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Job_Year_Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('published_at', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'year_count',
            },
        ),
        migrations.CreateModel(
            name='Job_Year_Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField()),
                ('published_at', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'year_salary',
            },
        ),
        migrations.CreateModel(
            name='Vacancy_From_HH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('skills', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'vacancy_from_hh',
            },
        ),
    ]
